import request from '../../utils/request.js'

const state = {
	cartList: [{
			isChecked: true,
			count: 4,
			'gspid': 0,
			'gid': 248732,
			'cateid': 7,
			'subject': '新西兰原装进口巅峰ZiwiPeak 鸡肉配方风干犬粮 1kg',
			'presubject': '新西兰原装进口巅峰ZiwiPeak 鸡肉配方风干犬粮 1kg',
			'formats': '',
			'formats_values': '',
			'photo': 'https://img2.epetbar.com/common/upload/commonfile/2020/02/03/202309_378516.jpg',
			'cover_img_for_notice': {
				'img_url': 'https://static.epetbar.com/static_www/goods_detail_dev/goods_with_video.png',
				'img_size': '50X50'
			},
			'sale_price': '405.00',
			'market_price': '499.00',
			'youhui_price': 0,
			'fm_shareid': 248744,
			'brandid': 725,
			'order': '',
			'replys': 269,
			'asks': 0,
			'sold': '售出:448',
			'unit': '袋',
			'stockmode': 2,
			'stock_now': 186,
			'stock': 186,
			'isBest': 0,
			'real_wid': 1,
			'virtual_wid': 1,
			'site': 0,
			'comments': '互动:(100%好评)',
			'dprice': '202.50元/斤',
			'country_photo': 'https://img2.epetbar.com/nowater/2016-08/12/16/f5b9321b7e88ed78e8bb0e226ac847a3.jpg',
			'with_me': '',
			'gtype_icon': {},
			'subject_tip': '',
			'goods_sign': 0,
			'goods_icon': '',
			'activityLabels': [],
			'activityIcons': [],
			'send_ware': '',
			'extend_pam': ''
		},
		{
			isChecked: false,
			count: 6,
			'gspid': 0,
			'gid': 199889,
			'cateid': 7,
			'subject': '新西兰原装进口 滋益巅峰Ziwi Peak 风干马鲛鱼羊肉配方狗粮 454g',
			'presubject': '新西兰原装进口 滋益巅峰Ziwi Peak 风干马鲛鱼羊肉配方狗粮 454g',
			'formats': '',
			'formats_values': '',
			'photo': 'https://img2.epetbar.com/common/upload/commonfile/2020/02/03/203516_879390.jpg',
			'cover_img_for_notice': {
				'img_url': 'https://static.epetbar.com/static_www/goods_detail_dev/goods_with_video.png',
				'img_size': '50X50'
			},
			'sale_price': '265.00',
			'market_price': '294.00',
			'youhui_price': 0,
			'fm_shareid': 199889,
			'brandid': 725,
			'order': '',
			'replys': 670,
			'asks': 11,
			'sold': '售出:230',
			'unit': '袋',
			'stockmode': 2,
			'stock_now': 19,
			'stock': 19,
			'isBest': 0,
			'real_wid': 1,
			'virtual_wid': 1,
			'site': 0,
			'comments': '互动:(100%好评)',
			'dprice': '294.44元/斤',
			'country_photo': 'https://img2.epetbar.com/nowater/2016-08/12/16/f5b9321b7e88ed78e8bb0e226ac847a3.jpg',
			'with_me': '',
			'gtype_icon': {},
			'subject_tip': '',
			'goods_sign': 0,
			'goods_icon': '',
			'activityLabels': [],
			'activityIcons': [],
			'send_ware': '',
			'extend_pam': ''
		},
		{
			isChecked: false,
			count: 10,
			'gspid': 0,
			'gid': 679879,
			'cateid': 7,
			'subject': '新西兰原装进口 卫塔卡夫Vitakraft 含牛肉羊肉配方犬粮 7kg',
			'presubject': '新西兰原装进口 卫塔卡夫Vitakraft 含牛肉羊肉配方犬粮 7kg',
			'formats': '',
			'formats_values': '',
			'photo': 'https://img2.epetbar.com/nowater/showcase/2021/12/31/2249259756213727.jpg',
			'cover_img_for_notice': {
				'img_url': 'https://static.epetbar.com/static_www/goods_detail_dev/goods_with_video.png',
				'img_size': '50X50'
			},
			'sale_price': '449.00',
			'market_price': '559.00',
			'youhui_price': 0,
			'fm_shareid': 679881,
			'brandid': 366,
			'order': '',
			'replys': 0,
			'asks': 0,
			'sold': '售出:238',
			'unit': '袋',
			'stockmode': 2,
			'stock_now': 8,
			'stock': 8,
			'isBest': 0,
			'real_wid': 1,
			'virtual_wid': 1,
			'site': 0,
			'comments': '互动:(100%好评)',
			'dprice': '32.07元/斤',
			'country_photo': 'https://img2.epetbar.com/nowater/2016-08/12/16/f5b9321b7e88ed78e8bb0e226ac847a3.jpg',
			'with_me': '',
			'gtype_icon': {},
			'subject_tip': '',
			'goods_sign': 0,
			'goods_icon': '',
			'activityLabels': [],
			'activityIcons': [],
			'send_ware': '',
			'extend_pam': ''
		}
	]
}

const mutations = {}

const actions = {}

const getters = {}

export default {
	state,
	mutations,
	actions,
	getters
}
